<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Teacher Performance Report - {{ $teacher->name }}</title>
    <style>
        body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; line-height: 1.5; margin: 0; padding: 40px; background: #fff; }
        .header { display: flex; justify-content: space-between; border-bottom: 2px solid #2563eb; padding-bottom: 20px; margin-bottom: 30px; }
        .school-info h1 { margin: 0 0 5px 0; font-size: 24px; color: #1e3a8a; }
        .school-info p { margin: 0; color: #64748b; font-size: 14px; }
        .report-meta { text-align: right; }
        .report-meta h2 { margin: 0 0 5px 0; font-size: 20px; color: #333; text-transform: uppercase; letter-spacing: 1px; }
        .report-meta p { margin: 0; font-size: 13px; color: #64748b; }
        
        .section-title { font-size: 16px; font-weight: bold; color: #1e3a8a; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; margin: 30px 0 15px 0; text-transform: uppercase; letter-spacing: 0.5px; }
        
        .stats-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin-bottom: 30px; }
        .stat-box { border: 1px solid #e2e8f0; border-radius: 8px; padding: 15px; text-align: center; }
        .stat-value { font-size: 24px; font-weight: bold; color: #1e293b; margin-bottom: 5px; }
        .stat-label { font-size: 12px; color: #64748b; text-transform: uppercase; }

        table { width: 100%; border-collapse: collapse; margin-bottom: 30px; font-size: 13px; }
        th { background: #f8fafc; text-align: left; padding: 10px; font-weight: bold; border-bottom: 2px solid #e2e8f0; color: #475569; }
        td { padding: 10px; border-bottom: 1px solid #e2e8f0; color: #333; }
        tr:nth-child(even) td { background: #f8fafc; }

        .footer { margin-top: 50px; padding-top: 20px; border-top: 1px solid #e2e8f0; text-align: center; font-size: 12px; color: #94a3b8; }
        
        .signature-area { margin-top: 50px; display: flex; justify-content: space-between; }
        .signature-line { width: 250px; border-top: 1px solid #333; margin-top: 50px; padding-top: 10px; text-align: center; font-weight: bold; font-size: 14px; }
        .signature-title { font-size: 12px; color: #64748b; font-weight: normal; }

        @media print {
            body { padding: 0; -webkit-print-color-adjust: exact; print-color-adjust: exact; }
            .no-print { display: none; }
        }
        
        .btn-print { display: inline-block; padding: 10px 20px; background: #2563eb; color: white; text-decoration: none; border-radius: 6px; font-weight: bold; margin-bottom: 20px; cursor: pointer; border: none; font-size: 14px; }
    </style>
</head>
<body>

    <div class="no-print" style="text-align: right;">
        <button onclick="window.print()" class="btn-print">Print / Save as PDF</button>
    </div>

    <div class="header">
        <div class="school-info">
            <h1>Teacher Performance Report</h1>
            <p>Generated by Early Warning System</p>
        </div>
        <div class="report-meta">
            <h2>{{ $teacher->name }}</h2>
            <p>{{ $teacher->email }}</p>
            <p>Generated: {{ now()->format('F j, Y - H:i') }}</p>
        </div>
    </div>

    <div class="stats-grid">
        <div class="stat-box">
            <div class="stat-value">{{ $engagementStatus }}</div>
            <div class="stat-label">System Engagement</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{{ number_format($totalAttendance) }}</div>
            <div class="stat-label">Attendance Records</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{{ number_format($totalReports) }}</div>
            <div class="stat-label">Behavioral Reports</div>
        </div>
        <div class="stat-box">
            <div class="stat-value">{{ $latestAttendance ? \Carbon\Carbon::parse($latestAttendance)->format('M d, Y') : 'N/A' }}</div>
            <div class="stat-label">Last Active Date</div>
        </div>
    </div>

    <div class="section-title">Recent Attendance Submissions</div>
    @if($recentAttendance->count() > 0)
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Student Name</th>
                    <th>Status Marked</th>
                </tr>
            </thead>
            <tbody>
                @foreach($recentAttendance as $att)
                    <tr>
                        <td>{{ \Carbon\Carbon::parse($att->date)->format('M d, Y') }}</td>
                        <td>{{ $att->student->name }} ({{ $att->student->student_id }})</td>
                        <td style="text-transform: capitalize;">{{ $att->status }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p style="font-size: 13px; color: #64748b; font-style: italic;">No attendance records found.</p>
    @endif

    <div class="section-title">Recent Behavioral Reports Filed</div>
    @if($recentReports->count() > 0)
        <table>
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Student Name</th>
                    <th>Report Type</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
                @foreach($recentReports as $report)
                    <tr>
                        <td>{{ $report->created_at->format('M d, Y') }}</td>
                        <td>{{ $report->student->name }}</td>
                        <td>{{ $report->report_type }}</td>
                        <td style="text-transform: capitalize;">{{ $report->status }}</td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    @else
        <p style="font-size: 13px; color: #64748b; font-style: italic;">No behavioral reports found.</p>
    @endif

    <div class="signature-area">
        <div>
            <div class="signature-line">
                {{ auth()->user()->name }}
                <div class="signature-title">System Administrator</div>
            </div>
        </div>
        <div>
            <div class="signature-line">
                {{ $teacher->name }}
                <div class="signature-title">Teacher Acknowledgment</div>
            </div>
        </div>
    </div>

    <div class="footer">
        <p>This is a system-generated report from the Student Referral & Early Warning System.</p>
        <p>&copy; {{ date('Y') }} All Rights Reserved.</p>
    </div>

    <script>
        window.onload = function() {
            window.print();
        };
    </script>
</body>
</html>
